app = 'orion-notes'
primary_region = 'ord'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[mounts]
  source = 'orion_data'
  destination = '/data'

[[services.http_checks]]
  interval = 10000
  grace_period = "10s"
  method = "get"
  path = "/api/health"
  protocol = "http"
  timeout = 2000

[env]
  ORION_DATA_DIR = '/data'
